Add license
kanisterio/errkit pull request #6
Opened 2024-03-25 15:17 UTC by e-sumin

Adding license.

2024-03-25 15:21 UTC, denisvmedia commented
@mlavi JFYI

2024-03-25 16:52 UTC, mlavi commented
We need to add our copyright on Line 190, I'll comment there now.

2024-03-25 16:54 UTC, mlavi requested changes
Please update line 190

2024-03-25 16:54 UTC, mlavi commented on LICENSE
> +   Copyright [yyyy] [name of copyright owner]
Please change to: Copyright 2024 Kasten, Inc.

2024-03-26 10:34 UTC, e-sumin commented on LICENSE
> +   Copyright [yyyy] [name of copyright owner]
Done

2024-03-26 10:54 UTC, denisvmedia commented on LICENSE
> +   Copyright Copyright 2024 Kasten, Inc.
2x Copyright.

2024-03-26 15:02 UTC, mlavi commented on LICENSE
> +   Copyright Copyright 2024 Kasten, Inc.
Almost there! :)

2024-03-26 15:35 UTC, e-sumin commented on LICENSE
> +   Copyright Copyright 2024 Kasten, Inc.
Thank you ! Fixed.

2024-03-26 15:52 UTC, mlavi approved these changes
LGTM

2024-03-26 16:00 UTC, denisvmedia approved these changes

2024-03-27 08:30 UTC, merged